app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("animals/", views.animals, name="animals"),
    path("doctors/", views.doctors, name="doctors"),
    path(
        "add_client_appointment/<int:appointment_id>/",
        views.add_client_appointment,
        name="add_client_appointment",
    ),
    path(
        "add_client_appointment_f/<int:appointment_id>/client/<int:client_id>/",
        views.add_client_appointment_f,
        name="add_client_appointment_f",
    ),
    path("doctors/<int:doctor_id>", views.doctor, name="doctor"),
    path(
        "reschedule/<int:appointment_id>/doctor/<int:doctor_id>/week/<int:week>",
        views.reschedule,
        name="reschedule",
    ),
    path(
        "reschedule_confirm/<int:appointment_id>/<int:slot_id>/<time>",
        views.reschedule_confirm,
        name="reschedule_confirm",
    ),
    path(
        "appointments_to_reschedule",
        views.appointments_to_reschedule,
        name="appointments_to_reschedule",
    ),
    path(
        "manage_slots/<int:doctor_id>/week/<int:week>/",
        views.manage_slots,
        name="manage_slots",
    ),
    path("animals/<int:animal_id>/disease/", views.disease, name="disease"),
    path(
        "animals/disease/<int:disease_id>",
        views.check_disease,
        name="check_disease",
    ),
    path("my_schedule/<int:week>/", views.my_schedule, name="my_schedule"),
    path("slot/<int:slot_id>", views.slot, name="slot"),
    path("delete_slot/<int:slot_id>", views.delete_slot, name="delete_slot"),
    path("add_slot/<int:doctor_id>/", views.add_slot, name="add_slot"),
    path("my_appointments/", views.my_appointments, name="my_appointments"),
    path(
        "appointment/<int:appointment_id>/",
        views.appointment,
        name="appointment",
    ),
    path(
        "appointment/<int:appointment_id>/delete",
        views.delete_appointment,
        name="delete_appointment",
    ),
    path(
        "edit_appointment/<int:appointment_id>/",
        views.edit_appointment,
        name="edit_appointment",
    ),
    path("make_appointment/", views.make_appointment, name="make_appointment"),
    path(
        "make_appointment_d/<int:service_id>/",
        views.make_appointment_d,
        name="make_appointment_d",
    ),
    path(
        "make_appointment_s/<int:service_id>/<int:doctor_id>/week/<int:week>/",
        views.make_appointment_s,
        name="make_appointment_s",
    ),
    path(
        "make_appointment_f/<int:service_id>/<int:slot_id>/<time>",
        views.make_appointment_f,
        name="make_appointment_f",
    ),
    path(
        "appointment/<int:appointment_id>/",
        views.appointment,
        name="appointment",
    ),
    path("browse_clients/", views.browse_clients, name="browse_clients"),
    path("browse_clients/<int:client_id>/", views.client, name="client"),
    path(
        "browse_clients/<int:client_id>/add_pet/",
        views.add_pet,
        name="add_pet",
    ),
    path(
        "browse_clients/pet/delete_pet/<int:pet_id>/",
        views.pet_delete,
        name="pet_delete",
    ),
    path(
        "browse_clients/pet/<int:pet_id>/add_disease",
        views.add_disease,
        name="add_disease",
    ),
    path(
        "browse_clients/medicine/delete_medicine/<int:medicine_id>/",
        views.medicine_delete,
        name="medicine_delete",
    ),
    path(
        "browse_clients/disease/delete_disease/<int:disease_id>/",
        views.disease_delete,
        name="disease_delete",
    ),
    path(
        "browse_clients/disease/<int:disease_id>/add_medicine/",
        views.add_medicine,
        name="add_medicine",
    ),
    path(
        "browse_clients/disease/edit_medicine/<int:medicine_id>/",
        views.edit_medicine,
        name="edit_medicine",
    ),
    path(
        "browse_clients/disease/edit_disease/<int:disease_id>/",
        views.edit_disease,
        name="edit_disease",
    ),
]

clinic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/levy/", admin.site.urls),
    path("users/", include("user.urls")),
    path("", include("app.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import include, path

from . import views

app_name = "user"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit", views.edit_profile, name="edit_profile"),
    path(
        "profile/change_password/",
        views.change_password,
        name="change_password",
    ),
]

app/templates/app/add_client_appointment_f.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
<h2>{% trans "Add client to the appointment"%}</h2>
{% endblock page_header %}
{%  block content%}
<div class="container p-3 my-3 border">
    <div class="container p-3 mx-3 bg-light text-black">
    <form method="POST">
        {% csrf_token %}
            <h3>{% trans "Do you want to add this client"%}:</h3>
            <h5>{{client.first_name}} {{client.last_name}}</h5>
            <h5>{{client.profile.phone_number}}</h5>
            <h5>{% trans "To"%}:</h3>
            <h6>{% trans "Date of visit"%}: {{appointment.date|date:"SHORT_DATE_FORMAT"}} {{appointment.start_time}}</h6>
            <h6>{% trans "Service"%}: {{appointment.service}}</h6>
            <h6>{% trans "Doctor"%}: {{appointment.doctor}}</h6>
            <p>{% trans "Additional information"%}: {{appointment.information|linebreaks}}</p>
        <h3>{% trans "This action can not be reversed!"%}</h3>    
        <button type="submit" class="btn btn-danger">{% trans "Yes"%}</button>
        <a class="btn btn-secondary" href="{% url 'app:add_client_appointment' appointment.id %}">{% trans "No"%}</a>
    </form>
</div>
{% endblock content %}

app/templates/app/add_slot.html
{% extends "app/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_header %}
<h2>{% trans "Add slots"%}</h2>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endblock page_header %}
{% block content %}
<div class="container p-3 my-3 bg-light text-black border">
    <div class = "offser-3 col-md-4">
        <h3>{{doctor}}</h3>
        <h4>{{doctor.speciality}}</h4>
        <p>{% trans "Days of visit"%}:</p>
        {% for slot in slots%}
        <div class="list-group-item list-group-item-light">{{slot.date|date:"l"}}
            {{slot.start_time}}-{{slot.end_time}}</div>
        {% empty %}
            <h5>{% trans "No slots"%}</h5>
        {%endfor%}
        <br>
        <form action = "{% url 'app:add_slot' doctor.id%}" method='post'>
            {% csrf_token %}
            {{day_form|crispy}}
            {{ slot_form|crispy }}
            <button name='submit'>{% trans "Add slot"%}</button>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>E-Clinic</title>
    {% load bootstrap4 %}
    {% load i18n %}
    {% load user_tags %}
    {% load static %}
    {% bootstrap_css%}
    {% bootstrap_javascript jquery="full"%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-custom navbar-expand-md navbar-light  mb-4 border">
      <a class="navbar-brand" href="{% url 'app:index'%}">
          E-Clinic</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto" id="links">
          {% if request.user.is_active and request.user.is_staff %}
            {% if request.user|has_group:"Doctors" %}
            <li class="nav-item" ><a class="nav-link"  href="{% url 'app:my_schedule' 0%}">{% trans "My schedule" %}</a></li>
            {% endif %}
            {% if request.user|has_group:"Admin" %}
            <li class="nav-item"><a class="nav-link" href="{% url 'app:browse_clients' %}">{% trans "Browse Clients" %}</a></li>
            {% endif %}
          {% else %}
          {% if user.is_authenticated%}
          <li class="nav-item"><a class="nav-link" href="{% url 'app:animals'%}">{% trans "My pets" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'app:my_appointments'%}">{% trans "My appointments" %}</a></li>
          {% endif %}
          {%endif%}
          <li class="nav-item"><a class="nav-link" href="{% url 'app:doctors'%}">{% trans "Our doctors" %}</a></li>
        </ul>
        <ul class="navbar-nav ml-auto" id="links">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">{% trans "Hello,"%} {{ user.first_name }}.</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">{% trans "Log out" %}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">{% trans "Register" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">{% trans "Log in" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main class="container">
      <div class="container p-4 my-4  text-black border rounded position-relative">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
    </main>
  </body>
</html>

app/templates/app/client.html
{% extends "app/base.html" %}
{% load i18n %}
{% load user_tags %}
{% load static %}
{% block page_header %}
    <h2>{{client.first_name}} {{client.last_name}}</h2>
    <p>{% trans "Email:" %} {{client.email}}</p>
    <p>{% trans "City:" %} {{client.profile.city}}</p>
    <p>{% trans "Phone number:" %} {{client.profile.phone_number}}</p>
{% endblock page_header %}
{% block content %}
{% if request.user|has_group:"Admin" %}
    <a class="list-group-item list-group-item-action list-group-item-success" href="{% url 'app:add_pet' client.id %}">{% trans "Add new pet"%}</a>
    {%endif%}
    <br>
    <h4>{% trans "Pets" %}:</h4>
    {% for animal in animals%}
        <a class="list-group-item list-group-item-action list-group-item-info" href="{% url 'app:disease' animal.id %}">{{animal}}</a>
        <p></p>
        {% empty %}
        <h5>{% trans "No pets"%}</h5>
    {%endfor%}
    <br>
    {% if appointments%}
    <h4>{% trans "Upcoming appointments"%}:</h4>
    {% for appointment in appointments %}
        <a class="list-group-item list-group-item-action list-group-item-success" href="{% url 'app:appointment' appointment.id %}">{{appointment.date|date:"SHORT_DATE_FORMAT"}} - {{appointment}}</a>
    {%endfor%}
    <br>
    {%endif%}
    {% if past_appointments%}
    <h4>{% trans "Past appointments" %}:</h4>
    {% for appointment in past_appointments %}
        <a class="list-group-item list-group-item-action list-group-item-success"
        href="javascript:showhide('{{appointment.id}}')">{{appointment.date|date:"SHORT_DATE_FORMAT"}} - {{appointment.animal}} - {{appointment.service}} - {{appointment.doctor}}</a>
        <div class="container p-3 mx-3 bg-light text-black" id="{{appointment.id}}" style="display: none;" >
            <h6>{% trans "Date of visit" %}: {{appointment.date|date:"SHORT_DATE_FORMAT"}} {{appointment.start_time}}</h5>
            <h6>{% trans "Service" %}: {{appointment.service}}</h6>
            <h6>{% trans "Doctor" %}: {{appointment.doctor}}</h6>
            <p>{% trans "Additional information" %}: {{appointment.information}}</p>
        </div>
    {% endfor %}
    {% endif %}
<script type="text/javascript" src="{% static 'js/show.js' %}"></script>
{% endblock content %}

app/templates/app/delete_appointment.html
{% extends "app/base.html" %}
{% load i18n %}
{% load user_tags %}
{% block page_header %}
{% endblock page_header %}
{%  block content%}
<div class="container p-3 my-3 border">
    <form method="POST">
        {% csrf_token %}
        <h1>{% trans "Do you want to delete"%}:</h1>
        {% if appointment.client%}
        <h5>{{appointment.client.first_name}} {{appointment.client.last_name}}</h5>
        {% endif %}
        {% if appointment.animal%}
        <h6>Pet: {{appointment.animal}}</h6>
        {% endif%}
        <h6>Date of visit: {{appointment.date|date:"SHORT_DATE_FORMAT"}} {{appointment.start_time}}</h5>
        <h6>Service: {{appointment.service}}</h6>
        <h6>Doctor: {{appointment.doctor}}</h6>
        <button type="submit" class="btn btn-danger">{% trans "Yes"%}</button>
        {% if request.user|has_group:"Admin" %}
        <a class="btn btn-secondary" href="{% url 'app:slot' appointment.slot.id%}">{% trans "No"%}</a>
        {% else%}
        <a class="btn btn-secondary" href="{% url 'app:my_appointments' %}">{% trans "No"%}</a>
        {% endif%}
    </form>
</div>
{% endblock content %}

app/templates/app/delete_disease.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
<h2><a class="text-dark" href="{% url 'app:disease' pet.id %}">{{pet}}</a></h2>
{% endblock page_header %}
{%  block content%}
<div class="container p-3 my-3 border">
    <form method="POST">
        {% csrf_token %}
        <h1>{% trans "Do you want to delete"%} {{disease.name}} {% trans "from"%} {{pet}}</h1>
        <button type="submit" class="btn btn-danger">{% trans "Yes"%}</button>
        <a class="btn btn-secondary" href="{% url 'app:disease' pet.id %}">{% trans "No"%}</a>
    </form>
</div>
{% endblock content %}

app/templates/app/delete_slot.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
<h2><a class="text-dark" href="{% url 'app:manage_slots' doctor.id 0%}">{{slot}}</a></h2>
{% endblock page_header %}
{%  block content%}
<div class="container p-3 my-3 border">
    <form method="POST">
        {% csrf_token %}
        <h2>{% trans "Do you want to delete"%}</h2>
        <h2>{{slot}} {% trans "from database?"%}</h2>
        <button type="submit" class="btn btn-danger">{% trans "Yes"%}</button>
        <a class="btn btn-secondary" href="{% url 'app:manage_slots' doctor.id 0%}">{% trans "No"%}</a>
    </form>
</div>
{% endblock content %}

app/templates/app/doctor.html
{% extends "app/base.html" %}
{% load i18n %}
{% load user_tags %}
{% block page_header %}
<h2>{% trans "Doctor"%} {{doctor}}</h2>
<style>
.md-avatar.size-4 {
  width: 320px;
  height: 300px;
}
</style>
{% endblock page_header %}
{% block content %}
<div class="container p-3 my-3 bg-light text-black border">
    <div class="row">
        <div class="col-auto p-3">
            <div class="card border-0 shadow">
                <img src="{{doctor.image.url}}" alt="Avatar" class="img-fluid md-avatar size-4">
            </div>
        </div>
        <div class="col p-3">
            <h5>{{doctor}}</h5>
            <h5>{% trans "Speciality"%}: {{doctor.speciality}}</h5>
            <h6>{% trans "Services"%}: </h6>
            {% for service in services %}
                <p>{{service}}</p>
            {% empty %}
                <p>{% trans "No services added yet."%}</p>
            {%endfor%}
        </div>
        <div class="col p-3">
            <h6>{% trans "Takes patients" %}:</h6>
            {% for slot in slots%}
            <div class="list-group-item list-group-item-light">{{slot.date|date:"l"}}
            {{slot.start_time}}-{{slot.end_time}}</div>
            {% empty %}
                <h5>{% trans "No slots"%}</h5>
            {%endfor%}
            <br>
            <div class="list-group">
                <a class="list-group-item list-group-item-action list-group-item-success"
                href="{% url 'app:make_appointment'%}">{% trans "Make appointment"%}</a></div>
            {% if request.user|has_group:"Admin" %}
            <br>
                <a class="list-group-item list-group-item-action list-group-item-success"
                href="{% url 'app:manage_slots' doctor.id 0%}">{% trans "Manage slots"%}</a>
            {% endif %} 
        </div>
    </div>
</div>
{% endblock content %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load i18n %}
{% block page_header %}
    <h1>{% trans "Welcome to the E-Clinic" %}</h1>
    <p>{% trans "After logging in you will see the user panel." %}</p>
{% endblock page_header %}
{% block content %}
    <p>User</p>
    <p>andrzej:pwiprojekt1</p>
    <p></p>
    <p>Admin/Staff</p>
    <p>admin:Zaliczenie</p>
    <a class="list-group-item list-group-item-action list-group-item-success"
        href="{% url 'app:make_appointment'%}">{% trans "Make appointment" %} </a>
    {% if no_slot_appointments%}
        <br>
        <a class="list-group-item list-group-item-action list-group-item-danger"
            href="{% url 'app:appointments_to_reschedule'%}">{% trans "Reschedule appointments" %}</a>
    {%endif%}
{% endblock content %}

app/templates/app/make_appointment.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
<h2>{% trans "Make appointment"%}</h2>
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}
{% endblock page_header %}
{% block content %}
<div class="list-group">
    <div class="dropdown">
      <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans "Choose vet service"%}
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for service in services%}
          <a class="dropdown-item"href="{% url 'app:make_appointment_d' service.id%}">{{service}}</a>
        {% empty %}
          <h5>{% trans "No services"%}</h5>
        {%endfor%}
      </div>
    </div>
</div>
{% endblock content %}

app/templates/app/manage_slots.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
{% load user_tags%}
<h2>{% trans "Manage slots"%}</h2>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endblock page_header %}
{% block content %}
<div class="container p-3 my-3 bg-light text-black border">
      <div class="col justify-content-md-center">
        <h5>{% trans "Doctor"%}: {{doctor}} - {{doctor.speciality}}</h5>
        <div class="col d-flex justify-content-center" style="padding: 0;"><h5>{% trans "Week"%}: {{first.day}}-{{first|date:"n"}} – {{last|date:"SHORT_DATE_FORMAT"}}</h5></div>
        <div class="row">
          {% if week != 0 %}
          <div class ="col align-self-start p-3"><a class="btn btn-success float-left"
            href="{% url 'app:manage_slots' doctor.id p_week %}">{% trans "Previous week"%}</a></div>
          {% endif %}
          <div class ="col align-self-end p-3"><a class="btn btn-success float-right"
              href="{% url 'app:manage_slots' doctor.id n_week %}">{% trans "Next week"%}</a></div>
        </div>
        <br>
        {% for slot in slots%}
          <div class="list-group-item list-group-item-light"><p>{{slot.date|date:'l'}} {{slot.date|date:'j'}} {{slot.date|date:'M'}}:
            {% check_appointments slot.id as checked%}
            {% if checked %}
            <a href="{% url 'app:slot' slot.id%}" class="text-primary">{% trans "Go to slot"%}</a>
            {% else %}
            {% trans "No appointments for this day"%}
            {% endif %}
            <a class='text-danger float-right' href="{% url 'app:delete_slot' slot.id %}">{% trans "Delete slot"%}</a></p>
          </div>
      {% empty %}
          <h5>{% trans "No slots for this week"%}</h5>
      {%endfor%}
      <br>
      <a class="list-group-item list-group-item-action list-group-item-success"
      href="{% url 'app:add_slot' doctor.id %}">{% trans "Add slot"%}</a>
    </div>
</div>
{% endblock content%}

app/templates/app/my_appointments.html
{% extends "app/base.html" %}
{% load i18n %}
{% load user_tags %}
{% block page_header %}
<h5>{% trans "My appointments"%}</h5>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endblock page_header %}
{% block content %}
{% if upcoming_appointment%}
<div class="container p-4 my-4 bg-light text-black border position-relative">
    <h3>{% trans "Date of visit: {{upcoming_appointment.start_time}} {{upcoming_appointment.date|date:"SHORT_DATE_FORMAT"}} </h3>
    {% if upcoming_appointment.animal %}
    <h4><a href="{% url 'app:disease' upcoming_appointment.animal.id %}">Pet: {{upcoming_appointment.animal}}</a></h4>
    {% endif %}
    <h5>{% trans "Service"%}: {{upcoming_appointment.service}}</h5>
    <h5>{% trans "Doctor"%}: {{upcoming_appointment.doctor}}</h5>
    {% if upcoming_appointment.information %}
    <p>{% trans "Additional information"%}: {{upcoming_appointment.information}}</p>
    {% endif %}
    <a class="btn btn-danger float-right" href="{% url 'app:delete_appointment' upcoming_appointment.id%}">{% trans "Delete appointment"%}</a>
    <br>
</div>
{% endif %}    
{% if appointments %}
<div class="list-group">
    {% for appointment in appointments%}
        <a class="list-group-item list-group-item-action list-group-item-success" href="{% url 'app:appointment' appointment.id%}">
            {{appointment.start_time}} {{appointment.date|date:"SHORT_DATE_FORMAT"}} {{appointment}}</a>
        <p></p>
    {%endfor%}
</div>
{%else%}
<div class="container p-3 my-3 bg-light text-black border">
    <h4>{% trans "No appointments registered" %}</h4>
</div>
{% endif %}
{% endblock content %}

app/templates/app/reschedule.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
{% load user_tags%}
<h2>{% trans "Reschedule appointment"%}</h2>
{% endblock page_header %}
{% block content %}
<div class="container p-3 mx-3 bg-light text-black ">
    <div class="row">
        <div class="col">
            <h5>{{appointment.client.first_name}} {{appointment.client.last_name}}</h5>
            <h6>{% trans "Pet"%}: {{appointment.animal}}</h6>
            <h6>{% trans "Date of visit"%}: {{appointment.date|date:"SHORT_DATE_FORMAT"}} {{appointment.start_time}}</h5>
            <h6>{% trans "Service"%}: {{appointment.service}}</h6>
            <h6>{% trans "Doctor"%}: {{appointment.doctor}}</h6>
            <p>{% trans "Additional information"%}: {{appointment.information}}</p>
        </div>
        <div class="col">
            {% if request.user|has_group:"Admin" %}
            <h5>{% trans "Client data"%}:</h5>
            <h6>{% trans "Email:" %} {{client.email}}</h6>
            <h6>{% trans "City:" %} {{client.profile.city}}</h6>
            <h6>{% trans "Phone number:" %} {{client.profile.phone_number}}</h6>
            {% endif%}
        </div>
    </div>
</div>
<div class="container p-3 my-3 bg-light text-black border">
    <div class="row">
      <div class="col-3">
        <img src= "{{doctor.image.url}}" class="img-fluid" >
        <h5>{% trans "Name"%}: {{doctor}}</h5>
        <h5>{% trans "Speciality"%}: {{doctor.speciality}}</h5>
      </div>
      <div class="col justify-content-md-center">
        <div class="row">
          {% if week != 0 %}
          <div class = 'col'><a class="list-group-item list-group-item-action list-group-item-success"
            href="{% url 'app:reschedule' appointment.id  doctor.id p_week%}">{% trans "Previous week"%}</a></div>
          {%else%}
          <div class = 'col'></div>
          {% endif %}
          <div class="col-6"><h5>Week: {{first.day}} {{first|date:"M"}} - {{last}}</h5></div>
          <div class = 'col'><a class="list-group-item list-group-item-action list-group-item-success"
              href="{% url 'app:reschedule' appointment.id doctor.id n_week%}">{% trans "Next week"%}</a></div>
        </div>
        <br>
        {% for slot in slots%}
          <div class="list-group-item list-group-item-light">{{slot.date|date:'l'}} {{slot.date|date:'j'}} {{slot.date|date:'M'}}:
            {%free_hours slot.id service.id as times%}
            {%for time in times%}
            <a href="{% url 'app:reschedule_confirm' appointment.id slot.id time %}" >{{time}}</a>
            {% endfor%}
          </div>
      {% empty %}
          <h5>{% trans "No slots"%}</h5>
      {%endfor%}
    </div>
  </div> 
</div>
<div class="row justify-content-md-center">
  {% for doc in doctors%}
      <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-0 shadow">
              <img src= "{{doc.image.url}}" class="card-img-top" alt="..." width="420" height="210">
              <div class="card-body text-center">
              <a href="{% url 'app:reschedule' appointment.id  doc.id 0%}" style="text-decoration: none;"><h5 class="card-title mb-0">{{doc}}</h5></a>
              <div class="card-text text-black-50">{{doc.speciality}}</div>
              </div>
          </div>
      </div>
  {%endfor%}
</div>
{% endblock content %}

app/templates/app/reschedule_confirm.html
{% extends "app/base.html" %}
{% load i18n %}
{% block page_header %}
<h2>Reschedule appointment</h2>
{% endblock page_header %}
{%  block content%}
<div class="container p-3 my-3 border">
    <form method="POST">
        {% csrf_token %}
        <h3>{% trans "Do you want to reschedule"%}</h3>
        <div class="container p-3 mx-3 bg-light text-black ">
            <div class="row">
                <div class="col">
                    <h4>From:</h4>
                    <h5>{{appointment.client.first_name}} {{appointment.client.last_name}}</h5>
                    <h6>{% trans "Pet"%}: {{appointment.animal}}</h6>
                    <h6>{% trans "Date of visit"%}: {{appointment.date}} {{appointment.start_time}}</h5>
                    <h6>{% trans "Service"%}: {{appointment.service}}</h6>
                    <h6>{% trans "Doctor"%}: {{appointment.doctor}}</h6>
                    <p>{% trans "Additional information"%}: {{appointment.information}}</p>
                </div>
                <div class="col">
                    <h4>{% trans "To"%}:</h4>
                    <h5>{{appointment.client.first_name}} {{appointment.client.last_name}}</h5>
                    <h6>{% trans "Pet"%}: {{appointment.animal}}</h6>
                    <h6>{% trans "Date of visit"%}: {{slot.date}} {{time}}</h5>
                    <h6>{% trans "Service"%}: {{appointment.service}}</h6>
                    <h6>{% trans "Doctor"%}: {{doctor}}</h6>
                    <p>{% trans "Additional information"%}: {{appointment.information}}</p>
                </div>
            </div>
            <button type="submit" class="btn btn-danger">{% trans "Yes"%}</button>
        <a class="btn btn-secondary" href="{% url 'app:reschedule' appointment.id appointment.doctor.id 0%}">{% trans "No"%}</a>
        </div>
    </form>
</div>
{% endblock content %}